theme: jekyll-theme-minimal
title: Zhi Chen
description: "<br/>Ph.D. Student<br/>Computer Science<br/>University of Illinois at Urbana-Champaign<br/><br/><h4>CONTACT INFO</h4><div><span style='display:inline-block;width:25%;'>Address: </span><span style='display:inline-block;width:75%;'>Thomas M. Siebel Center 201 North Goodwin Avenue Urbana, IL 61801</span></div><br/>Email: zhic4@illinois.edu"
logo: /data/0.jpg
show_downloads: true
