theme: jekyll-theme-minimal
title: Zhi Chen
description: "Ph.D. Student<br/>Computer Science<br/>University of Illinois at Urbana-Champaign <br/><h3>CONTACT INFO</h3><br/>Address: Thomas M. Siebel Center 201 North Goodwin Avenue Urbana, IL 61801<br/>Email: zhic4@illinois.edu"
logo: /data/0.jpeg
show_downloads: true
